# Generated by Django 5.0 on 2023-12-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('speed_rate', models.IntegerField()),
                ('comfort_rate', models.IntegerField()),
                ('price_rate', models.IntegerField()),
            ],
        ),
    ]
